// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsbP84ByrVLPY1MuiDtQUgAv9-RF1_fQ',
    appId: '1:729142601350:web:b190977b210e1dfca3d307',
    messagingSenderId: '729142601350',
    projectId: 'my-note-a66f2',
    authDomain: 'my-note-a66f2.firebaseapp.com',
    storageBucket: 'my-note-a66f2.appspot.com',
    measurementId: 'G-0GPYNWBRDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAWa40eJho6Z25Ad0lGV6lzsqNF1eNW0',
    appId: '1:729142601350:android:14abd8858e301881a3d307',
    messagingSenderId: '729142601350',
    projectId: 'my-note-a66f2',
    storageBucket: 'my-note-a66f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCho3tAOrGkru19Imnik-KtBcnBdxvO9ho',
    appId: '1:729142601350:ios:e52913056d5d87a1a3d307',
    messagingSenderId: '729142601350',
    projectId: 'my-note-a66f2',
    storageBucket: 'my-note-a66f2.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCho3tAOrGkru19Imnik-KtBcnBdxvO9ho',
    appId: '1:729142601350:ios:661008da2db6e67ea3d307',
    messagingSenderId: '729142601350',
    projectId: 'my-note-a66f2',
    storageBucket: 'my-note-a66f2.appspot.com',
    iosBundleId: 'com.example.noteapp.RunnerTests',
  );
}
